component: website
name: site

inputs:
  # React application. "hook" runs before deployment to build the source code.  "dist" is the built artifact directory which is uploaded.
  src:
    src: ./
    hook: yarn build
    dist: build
  # Enable this when you want to set a custom domain.
  # domain: ${env:domain}
  env:
    REACT_APP_PUBLIC_API_URL: ${env:REACT_APP_PUBLIC_API_URL}
