component: website
name: site

inputs:
  # React application. "hook" runs before deployment to build the source code.  "dist" is the built artifact directory which is uploaded.
  src:
    src: ./
    hook: yarn build
    dist: build
  # Enable this when you want to set a custom domain.
  # domain: ${env:domain}
  region: ap-northeast-1
  env:
    REACT_APP_PUBLIC_API_URL: ${env:REACT_APP_PUBLIC_API_URL}
    REACT_APP_SHOPIFY_API_KEY: ${env:REACT_APP_SHOPIFY_API_KEY}
    REACT_APP_SHOPIFY_SECRET_KEY: ${env:REACT_APP_SHOPIFY_SECRET_KEY}
    REACT_APP_SCOPES: ${env:REACT_APP_SCOPES}
    REACT_APP_APPLICATION_URL: ${env:REACT_APP_APPLICATION_URL}
