component: express
name: api
custom:
  stage: dev

inputs:
  src: ./
  roleName: ${output:permissions.name}
  # domain: api.${env:domain}
  region: ap-northeast-1
  env:
    DB: ${output:database.name}
    DB_INDEX1: ${output:database.indexes.gsi1.name}
    # A secret token to sign the JWT tokens with.
    TOKEN_SECRET: ${env:tokenSecret}
