component: express
name: api
custom:
  stage: dev

inputs:
  src: ./
  roleName: ${output:permissions.name}
  # domain: api.${env:domain}
  region: ap-northeast-1
  env:
    APP_NAME: ${app}
    SHOPIFY_API_KEY: ${env:SHOPIFY_API_KEY}
    SHOPIFY_API_SECRET: ${env:SHOPIFY_API_SECRET}
