component: express
name: api
custom:
  stage: dev

inputs:
  src: ./
  roleName: ${output:permissions.name}
  # domain: api.${env:domain}
  region: ap-northeast-1
  env:
    DB: ${output:database.name}
    DB_INDEX1: ${output:database.indexes.gsi1.name}
    TOKEN_SECRET: ${env:tokenSecret}
    AWS_PROJECT_REAGION: ${env:AWS_PROJECT_REAGION}
    AWS_COGNITO_IDENTITY_POOL_ID: ${env:AWS_COGNITO_IDENTITY_POOL_ID}
    AWS_COGNITO_REGION: ${env:AWS_COGNITO_REGION}
    AWS_USER_POOLS_ID: ${env:AWS_USER_POOLS_ID}
    AWS_USER_POOLS_WEB_CLIENT_ID: ${env:AWS_USER_POOLS_WEB_CLIENT_ID}
